/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edd;

import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author nimas
 */
public class NewJFrameEDD extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameEDD
     */
    public NewJFrameEDD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtlrmp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        poaweeks = new javax.swing.JTextField();
        txtedddd = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtlrmpyyyy = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtlrmpmm = new javax.swing.JTextField();
        txtlrmpdd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txteddmm = new javax.swing.JTextField();
        txteddyyyy = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();

        jLabel6.setText("jLabel6");

        jLabel2.setText("DOV");

        jButton2.setText("CLICK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        txtlrmp.setText("   LRMP");
        jPanel1.add(txtlrmp);
        txtlrmp.setBounds(33, 69, 44, 28);

        jLabel3.setText("OBSTETRICS  CALCULATOR");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(208, 8, 159, 27);

        jLabel4.setText("POA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(33, 177, 82, 24);

        jLabel5.setText("EDD");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(25, 264, 70, 31);

        poaweeks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poaweeksActionPerformed(evt);
            }
        });
        jPanel1.add(poaweeks);
        poaweeks.setBounds(147, 182, 67, 14);

        txtedddd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteddddActionPerformed(evt);
            }
        });
        jPanel1.add(txtedddd);
        txtedddd.setBounds(113, 233, 45, 20);

        jTextField4.setText("DATE");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4);
        jTextField4.setBounds(157, 53, 32, 20);

        jTextField5.setText("MONTH");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5);
        jTextField5.setBounds(220, 53, 43, 20);

        jTextField6.setText("YEAR");
        jPanel1.add(jTextField6);
        jTextField6.setBounds(273, 53, 40, 20);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(316, 89, 0, 0);
        jPanel1.add(txtlrmpyyyy);
        txtlrmpyyyy.setBounds(271, 79, 41, 20);

        jButton1.setText("CALCULATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(147, 204, 89, 23);
        jPanel1.add(txtlrmpmm);
        txtlrmpmm.setBounds(220, 79, 33, 20);
        jPanel1.add(txtlrmpdd);
        txtlrmpdd.setBounds(157, 79, 32, 20);

        jLabel7.setText("weeks");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(232, 182, 30, 14);
        jPanel1.add(txteddmm);
        txteddmm.setBounds(198, 233, 38, 20);
        jPanel1.add(txteddyyyy);
        txteddyyyy.setBounds(286, 233, 39, 20);

        jTextField12.setText("DATE");
        jPanel1.add(jTextField12);
        jTextField12.setBounds(105, 269, 45, 20);

        jTextField13.setText("MONTH");
        jPanel1.add(jTextField13);
        jTextField13.setBounds(206, 269, 42, 20);

        jTextField14.setText("YEAR");
        jPanel1.add(jTextField14);
        jTextField14.setBounds(286, 269, 39, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void txteddddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteddddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteddddActionPerformed

    private void poaweeksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poaweeksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poaweeksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int dd;
        int yyyy;
        int mm;
try{
        dd = Integer.parseInt(txtlrmpdd.getText());}
           
        catch (Exception e){
           
            JOptionPane.showMessageDialog(null, "please enter the corect date");
            txtlrmpdd.requestFocus();
            return;
        }



       try{ mm = Integer.parseInt(txtlrmpmm.getText()) - 1;}catch (Exception e){JOptionPane.showMessageDialog(null, "please enter the corect date");
            txtlrmpmm.requestFocus();
            return;}
        try {
            yyyy = Integer.parseInt(txtlrmpyyyy.getText().trim());
        } catch (Exception e){
           
            JOptionPane.showMessageDialog(null, "please enter the corect year");
            txtlrmpyyyy.requestFocus();
            return;
        }
                
        Calendar c = Calendar.getInstance();
            c.set(Calendar.YEAR, yyyy);
            c.set(Calendar.MONTH, mm);
            c.set(Calendar.DATE, dd);
            Date lrmp = c.getTime();
            Date today = new Date();

            c.add(Calendar.DATE, 280);

            txteddyyyy.setText(c.getTime().toString());
            txteddyyyy.setText(c.get(Calendar.YEAR) + "");
            txteddmm.setText((c.get(Calendar.MONTH) + 1) + "");
            txtedddd.setText(c.get(Calendar.DATE) + "");
            Long poaLong = (today.getTime() - lrmp.getTime()) / (1000 * 60 * 60 * 24 * 7);
            poaweeks.setText(poaLong + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameEDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameEDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField poaweeks;
    private javax.swing.JTextField txtedddd;
    private javax.swing.JTextField txteddmm;
    private javax.swing.JTextField txteddyyyy;
    private javax.swing.JLabel txtlrmp;
    private javax.swing.JTextField txtlrmpdd;
    private javax.swing.JTextField txtlrmpmm;
    private javax.swing.JTextField txtlrmpyyyy;
    // End of variables declaration//GEN-END:variables
}
